# requires dhtnode docker image already present in the cache
# start with `docker-compose -f docker-compose-example.yml up
version: '2'
services:
  dhtnode:
    image: sociomantictsunami/dhtnode
    ports:
      - "10000:10000"
    volumes:
      - "dhtdata:/src/dhtnode/dhtnode-0/data"
volumes:
  dhtdata:
